
import { Food } from "./types";

export const mockFoods: Food[] = [
  {
    id: "4",
    name: "Organic Bananas",
    brand: "Waitrose",
    calories: 95,
    protein: 1.2,
    carbs: 22,
    fat: 0.3,
    servingSize: "1 banana (118g)",
    barcode: "0000000000000",
    supermarket: "Waitrose",
    category: "Fruits & Vegetables"
  },
  {
    id: "5",
    name: "Pink Lady Apples",
    brand: "M&S",
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    servingSize: "1 apple (100g)",
    supermarket: "M&S",
    category: "Fruits & Vegetables"
  },
  {
    id: "9",
    name: "Coca Cola Original",
    brand: "Coca Cola",
    calories: 42,
    protein: 0,
    carbs: 10.6,
    fat: 0,
    servingSize: "100ml",
    supermarket: "All Supermarkets",
    category: "Drinks"
  },
  {
    id: "10",
    name: "Orange Juice Smooth",
    brand: "Tropicana",
    calories: 42,
    protein: 0.5,
    carbs: 9.1,
    fat: 0,
    servingSize: "100ml",
    supermarket: "All Supermarkets",
    category: "Drinks"
  },
  {
    id: "11",
    name: "Lightly Salted Crisps",
    brand: "Walkers",
    calories: 526,
    protein: 6.1,
    carbs: 51,
    fat: 32,
    servingSize: "100g",
    supermarket: "All Supermarkets",
    category: "Snacks"
  },
  {
    id: "12",
    name: "Dark Chocolate 70%",
    brand: "Lindt Excellence",
    calories: 545,
    protein: 7.5,
    carbs: 45,
    fat: 37.5,
    servingSize: "100g",
    supermarket: "All Supermarkets",
    category: "Snacks"
  },
  {
    id: "14",
    name: "Porridge Oats",
    brand: "Quaker",
    calories: 372,
    protein: 11.4,
    carbs: 60,
    fat: 8,
    servingSize: "100g",
    supermarket: "All Supermarkets",
    category: "Cereals"
  },
  {
    id: "16",
    name: "Basmati Rice",
    brand: "Tilda",
    calories: 350,
    protein: 8.6,
    carbs: 77.6,
    fat: 1.3,
    servingSize: "100g dry",
    supermarket: "All Supermarkets",
    category: "Pasta & Rice"
  },
  {
    id: "17",
    name: "Mayonnaise",
    brand: "Hellmann's",
    calories: 721,
    protein: 1.1,
    carbs: 1.3,
    fat: 79,
    servingSize: "100g",
    supermarket: "All Supermarkets",
    category: "Condiments"
  },
  {
    id: "18",
    name: "Garden Peas",
    brand: "Birds Eye",
    calories: 68,
    protein: 5.2,
    carbs: 9.1,
    fat: 0.4,
    servingSize: "100g",
    supermarket: "All Supermarkets",
    category: "Frozen Foods"
  },
  {
    id: "20",
    name: "Cheddar Cheese",
    brand: "Cathedral City",
    calories: 403,
    protein: 24.9,
    carbs: 0.1,
    fat: 33.4,
    servingSize: "100g",
    supermarket: "All Supermarkets",
    category: "Dairy & Eggs"
  },
  {
    id: "21",
    name: "Almonds",
    brand: "Whitworths",
    calories: 579,
    protein: 21.2,
    carbs: 21.6,
    fat: 49.9,
    servingSize: "100g",
    supermarket: "All Supermarkets",
    category: "Snacks"
  },
  {
    id: "23",
    name: "Baked Beans",
    brand: "Heinz",
    calories: 77,
    protein: 4.9,
    carbs: 12.9,
    fat: 0.2,
    servingSize: "100g",
    supermarket: "All Supermarkets",
    category: "Condiments"
  },
  {
    id: "24",
    name: "Ice Cream Vanilla",
    brand: "Haagen-Dazs",
    calories: 244,
    protein: 3.5,
    carbs: 23.4,
    fat: 15.4,
    servingSize: "100g",
    supermarket: "All Supermarkets",
    category: "Frozen Foods"
  },
  {
    id: "26",
    name: "Iced Latte",
    brand: "Starbucks",
    calories: 70,
    protein: 3,
    carbs: 10,
    fat: 2,
    servingSize: "100ml",
    supermarket: "All Supermarkets",
    category: "Drinks"
  },
  {
    id: "27",
    name: "Mushroom Soup",
    brand: "Campbells",
    calories: 67,
    protein: 1.5,
    carbs: 8.2,
    fat: 3.1,
    servingSize: "100ml",
    supermarket: "All Supermarkets",
    category: "Ready Meals"
  },
  {
    id: "28",
    name: "Granola",
    brand: "Dorset",
    calories: 452,
    protein: 10.7,
    carbs: 57.1,
    fat: 18.7,
    servingSize: "100g",
    supermarket: "All Supermarkets",
    category: "Cereals"
  },
  {
    id: "29",
    name: "Greek Yogurt 0% Fat",
    brand: "Fage",
    calories: 54,
    protein: 10.3,
    carbs: 3.0,
    fat: 0,
    servingSize: "100g",
    supermarket: "All Supermarkets",
    category: "Dairy & Eggs"
  }
];

